/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthLayoutRouteRouteImport } from './routes/_authLayout/route'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as ApiSendVerificationEmailRouteRouteImport } from './routes/api/send-verification-email/route'
import { Route as ApiSendPasswordResetEmailRouteRouteImport } from './routes/api/send-password-reset-email/route'
import { Route as ProtectedSessionsIndexRouteImport } from './routes/_protected/sessions/index'
import { Route as ProtectedSecurityIndexRouteImport } from './routes/_protected/security/index'
import { Route as ProtectedDangerIndexRouteImport } from './routes/_protected/danger/index'
import { Route as ProtectedAccountsIndexRouteImport } from './routes/_protected/accounts/index'
import { Route as ProtectedAccountIndexRouteImport } from './routes/_protected/account/index'
import { Route as AuthLayoutSignUpIndexRouteImport } from './routes/_authLayout/sign-up/index'
import { Route as AuthLayoutResetPasswordIndexRouteImport } from './routes/_authLayout/reset-password/index'
import { Route as AuthLayoutLoginIndexRouteImport } from './routes/_authLayout/login/index'
import { Route as AuthLayoutForgotPasswordIndexRouteImport } from './routes/_authLayout/forgot-password/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRouteRoute = AuthLayoutRouteRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendVerificationEmailRouteRoute =
  ApiSendVerificationEmailRouteRouteImport.update({
    id: '/api/send-verification-email',
    path: '/api/send-verification-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSendPasswordResetEmailRouteRoute =
  ApiSendPasswordResetEmailRouteRouteImport.update({
    id: '/api/send-password-reset-email',
    path: '/api/send-password-reset-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedSessionsIndexRoute = ProtectedSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSecurityIndexRoute = ProtectedSecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDangerIndexRoute = ProtectedDangerIndexRouteImport.update({
  id: '/danger/',
  path: '/danger/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAccountsIndexRoute = ProtectedAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAccountIndexRoute = ProtectedAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthLayoutSignUpIndexRoute = AuthLayoutSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const AuthLayoutResetPasswordIndexRoute =
  AuthLayoutResetPasswordIndexRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => AuthLayoutRouteRoute,
  } as any)
const AuthLayoutLoginIndexRoute = AuthLayoutLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const AuthLayoutForgotPasswordIndexRoute =
  AuthLayoutForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => AuthLayoutRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/send-password-reset-email': typeof ApiSendPasswordResetEmailRouteRoute
  '/api/send-verification-email': typeof ApiSendVerificationEmailRouteRoute
  '/privacy': typeof PrivacyIndexRoute
  '/terms': typeof TermsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/forgot-password': typeof AuthLayoutForgotPasswordIndexRoute
  '/login': typeof AuthLayoutLoginIndexRoute
  '/reset-password': typeof AuthLayoutResetPasswordIndexRoute
  '/sign-up': typeof AuthLayoutSignUpIndexRoute
  '/account': typeof ProtectedAccountIndexRoute
  '/accounts': typeof ProtectedAccountsIndexRoute
  '/danger': typeof ProtectedDangerIndexRoute
  '/security': typeof ProtectedSecurityIndexRoute
  '/sessions': typeof ProtectedSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/api/send-password-reset-email': typeof ApiSendPasswordResetEmailRouteRoute
  '/api/send-verification-email': typeof ApiSendVerificationEmailRouteRoute
  '/privacy': typeof PrivacyIndexRoute
  '/terms': typeof TermsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/forgot-password': typeof AuthLayoutForgotPasswordIndexRoute
  '/login': typeof AuthLayoutLoginIndexRoute
  '/reset-password': typeof AuthLayoutResetPasswordIndexRoute
  '/sign-up': typeof AuthLayoutSignUpIndexRoute
  '/account': typeof ProtectedAccountIndexRoute
  '/accounts': typeof ProtectedAccountsIndexRoute
  '/danger': typeof ProtectedDangerIndexRoute
  '/security': typeof ProtectedSecurityIndexRoute
  '/sessions': typeof ProtectedSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authLayout': typeof AuthLayoutRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/api/send-password-reset-email': typeof ApiSendPasswordResetEmailRouteRoute
  '/api/send-verification-email': typeof ApiSendVerificationEmailRouteRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authLayout/forgot-password/': typeof AuthLayoutForgotPasswordIndexRoute
  '/_authLayout/login/': typeof AuthLayoutLoginIndexRoute
  '/_authLayout/reset-password/': typeof AuthLayoutResetPasswordIndexRoute
  '/_authLayout/sign-up/': typeof AuthLayoutSignUpIndexRoute
  '/_protected/account/': typeof ProtectedAccountIndexRoute
  '/_protected/accounts/': typeof ProtectedAccountsIndexRoute
  '/_protected/danger/': typeof ProtectedDangerIndexRoute
  '/_protected/security/': typeof ProtectedSecurityIndexRoute
  '/_protected/sessions/': typeof ProtectedSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/send-password-reset-email'
    | '/api/send-verification-email'
    | '/privacy'
    | '/terms'
    | '/api/auth/$'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/account'
    | '/accounts'
    | '/danger'
    | '/security'
    | '/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/send-password-reset-email'
    | '/api/send-verification-email'
    | '/privacy'
    | '/terms'
    | '/api/auth/$'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/account'
    | '/accounts'
    | '/danger'
    | '/security'
    | '/sessions'
  id:
    | '__root__'
    | '/_authLayout'
    | '/_protected'
    | '/api/send-password-reset-email'
    | '/api/send-verification-email'
    | '/privacy/'
    | '/terms/'
    | '/api/auth/$'
    | '/_authLayout/forgot-password/'
    | '/_authLayout/login/'
    | '/_authLayout/reset-password/'
    | '/_authLayout/sign-up/'
    | '/_protected/account/'
    | '/_protected/accounts/'
    | '/_protected/danger/'
    | '/_protected/security/'
    | '/_protected/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLayoutRouteRoute: typeof AuthLayoutRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  ApiSendPasswordResetEmailRouteRoute: typeof ApiSendPasswordResetEmailRouteRoute
  ApiSendVerificationEmailRouteRoute: typeof ApiSendVerificationEmailRouteRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-verification-email': {
      id: '/api/send-verification-email'
      path: '/api/send-verification-email'
      fullPath: '/api/send-verification-email'
      preLoaderRoute: typeof ApiSendVerificationEmailRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-password-reset-email': {
      id: '/api/send-password-reset-email'
      path: '/api/send-password-reset-email'
      fullPath: '/api/send-password-reset-email'
      preLoaderRoute: typeof ApiSendPasswordResetEmailRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/sessions/': {
      id: '/_protected/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof ProtectedSessionsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/security/': {
      id: '/_protected/security/'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof ProtectedSecurityIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/danger/': {
      id: '/_protected/danger/'
      path: '/danger'
      fullPath: '/danger'
      preLoaderRoute: typeof ProtectedDangerIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/accounts/': {
      id: '/_protected/accounts/'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof ProtectedAccountsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/account/': {
      id: '/_protected/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_authLayout/sign-up/': {
      id: '/_authLayout/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthLayoutSignUpIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/reset-password/': {
      id: '/_authLayout/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthLayoutResetPasswordIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/login/': {
      id: '/_authLayout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/forgot-password/': {
      id: '/_authLayout/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthLayoutForgotPasswordIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthLayoutRouteRouteChildren {
  AuthLayoutForgotPasswordIndexRoute: typeof AuthLayoutForgotPasswordIndexRoute
  AuthLayoutLoginIndexRoute: typeof AuthLayoutLoginIndexRoute
  AuthLayoutResetPasswordIndexRoute: typeof AuthLayoutResetPasswordIndexRoute
  AuthLayoutSignUpIndexRoute: typeof AuthLayoutSignUpIndexRoute
}

const AuthLayoutRouteRouteChildren: AuthLayoutRouteRouteChildren = {
  AuthLayoutForgotPasswordIndexRoute: AuthLayoutForgotPasswordIndexRoute,
  AuthLayoutLoginIndexRoute: AuthLayoutLoginIndexRoute,
  AuthLayoutResetPasswordIndexRoute: AuthLayoutResetPasswordIndexRoute,
  AuthLayoutSignUpIndexRoute: AuthLayoutSignUpIndexRoute,
}

const AuthLayoutRouteRouteWithChildren = AuthLayoutRouteRoute._addFileChildren(
  AuthLayoutRouteRouteChildren,
)

interface ProtectedRouteRouteChildren {
  ProtectedAccountIndexRoute: typeof ProtectedAccountIndexRoute
  ProtectedAccountsIndexRoute: typeof ProtectedAccountsIndexRoute
  ProtectedDangerIndexRoute: typeof ProtectedDangerIndexRoute
  ProtectedSecurityIndexRoute: typeof ProtectedSecurityIndexRoute
  ProtectedSessionsIndexRoute: typeof ProtectedSessionsIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAccountIndexRoute: ProtectedAccountIndexRoute,
  ProtectedAccountsIndexRoute: ProtectedAccountsIndexRoute,
  ProtectedDangerIndexRoute: ProtectedDangerIndexRoute,
  ProtectedSecurityIndexRoute: ProtectedSecurityIndexRoute,
  ProtectedSessionsIndexRoute: ProtectedSessionsIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRouteRoute: AuthLayoutRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  ApiSendPasswordResetEmailRouteRoute: ApiSendPasswordResetEmailRouteRoute,
  ApiSendVerificationEmailRouteRoute: ApiSendVerificationEmailRouteRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
